Add reference files for example outputs used in the tutorial.
	* doc/doc.mk: add new path variables.

	* doc/tutorial/figures/ima2d-rot-1.ppm
	* doc/tutorial/figures/ima2d-rot-2.ppm
	* doc/tutorial/outputs/borderthickness.txt
	* doc/tutorial/outputs/dpoint-1.txt
	* doc/tutorial/outputs/graph-data-full.txt
	* doc/tutorial/outputs/ima-has.txt
	* doc/tutorial/outputs/ima-size.txt
	* doc/tutorial/outputs/ima2d-1.txt
	* doc/tutorial/outputs/ima2d-decl-2-blobs-full.txt
	* doc/tutorial/outputs/ima2d-rot.txt
	* doc/tutorial/outputs/labeling-compute-full.txt
	* doc/tutorial/outputs/logical-not.txt
	* doc/tutorial/outputs/paste-call-1.txt
	* doc/tutorial/outputs/point-1.txt: reference files.

	* doc/tutorial/samples/Makefile.am: diff the generated files to their
	reference.

git-svn-id: https://svn.lrde.epita.fr/svn/oln/trunk@2941 4aad255d-cdde-0310-9447-f3009e2ae8c0

diff --git a/milena/doc/tutorial/samples/Makefile.am b/milena/doc/tutorial/samples/Makefile.am
--- a/milena/doc/tutorial/samples/Makefile.am
+++ b/milena/doc/tutorial/samples/Makefile.am
@@ -5,6 +5,7 @@ include $(top_srcdir)/milena/doc/doc.mk
 bin_PROGRAMS =			\
   borderthickness 		\
   dpoint-1 			\
+  graph-data-full 		\
   ima-has 			\
   ima-size 			\
   ima2d-1 			\
@@ -17,6 +18,7 @@ bin_PROGRAMS =			\
 
 borderthickness_SOURCES = borderthickness.cc
 dpoint_1_SOURCES = dpoint-1.cc
+graph_data_full_SOURCES = graph-data-full.cc
 ima_has_SOURCES = ima-has.cc
 ima_size_SOURCES = ima-size.cc
 ima2d_1_SOURCES = ima2d-1.cc
@@ -27,15 +29,53 @@ logical_not_SOURCES = logical-not.cc
 paste_call_1_SOURCES = paste-call-1.cc
 point_1_SOURCES = point-1.cc
 
-all:
-	mkdir -p $(OUTPUTS_DIR) 
-	mkdir -p $(FIGURES_DIR) 
-	@failcom='exit 1'; 					\
-	list='$(bin_PROGRAMS)'; for bin in $$list; do 		\
-	  echo "Running $$bin"; 				\
-	  ./$$bin > $(OUTPUTS_DIR)/$$bin.txt || eval $$failcom; \
-	done; 
+all: clean-png-figures
+	mkdir -p $(OUTPUTS_BUILDDIR) 
+	mkdir -p $(FIGURES_BUILDDIR) 
+	@failcom='exit 1'; 						\
+	list='$(bin_PROGRAMS)'; for bin in $$list; do 			\
+	  echo "Running $$bin"; 					\
+	  ./$$bin > $(OUTPUTS_BUILDDIR)/$$bin.txt || eval $$failcom; 	\
+	done;								\
+ 	has_txt_diff="";						\
+ 	txtlist="$(OUTPUTS_BUILDDIR)/*"; for txt in $$txtlist; do 	\
+ 	  echo "Diff `basename $$txt`";					\
+ 	  diff $$txt $(OUTPUTS_SRCDIR)/`basename $$txt` >/dev/null 2>&1	\
+ 		|| has_txt_diff+=" `basename $$txt`";	\
+ 	done;								\
+ 	has_fig_diff="";						\
+ 	figlist="$(FIGURES_BUILDDIR)/*"; for fig in $$figlist; do 	\
+ 	  echo "Diff `basename $$fig`";					\
+ 	  diff $$fig $(FIGURES_SRCDIR)/`basename $$fig` >/dev/null 2>&1 \
+ 		|| has_fig_diff=" `basename $$fig`";	\
+ 	done; 								\
+	(test -z "$$has_txt_diff" && test -z "$$has_fig_diff")		\
+	 || (echo "--------";						\
+	     echo "ERROR: please check if the tutorial needs an update.";\
+	     echo "       The following files differ from their \
+reference or their reference file does not exist:";  			\
+	     echo "--------"; 						\
+  	     echo "* Outputs:";						\
+  	     echo "";							\
+  	     echo "$$has_txt_diff"; 					\
+  	     echo "";							\
+	     echo "--------"; 						\
+  	     echo "* Figures:"; 						\
+  	     echo "";							\
+  	     echo "$$has_fig_diff"; 					\
+  	     echo "";							\
+	     echo "--------"; 						\
+  	     echo "* Please update the reference files located in:";	\
+  	     echo "";							\
+	     echo " $(OUTPUTS_SRCDIR)"; 					\
+	     echo " $(FIGURES_SRCDIR)"; 					\
+  	     echo "";							\
+  	     eval $$failcom);
+
 
 clean-local:
-	rm -Rf $(OUTPUTS_DIR) $(FIGURES_DIR)
+	rm -Rf $(OUTPUTS_BUILDDIR) $(FIGURES_BUILDDIR)
 
+## Clean up converted images. (*.p*m -> *.png)
+clean-png-figures:
+	rm -f $(FIGURES_BUILDDIR)/*.png
